Add a tutorial for deploying Milvus on KubeSphere
milvus-io/bootcamp pull request #1035
Opened 2022-03-18 16:13 UTC by Bennu-Li

Signed-off-by: Bennu <yunmei.li@zilliz.com>

- [ ] A reference to a related issue in your repository.
  
  Each PR is related to an issue, and you need to list that issue.

- [ ] A description of the changes proposed in the pull request.

  A brief introduction to this PR.

- [ ] Add delight to the experience when all tasks are complete :tada:

2022-03-18 17:25 UTC, ss892714028 requested changes

2022-03-18 17:25 UTC, ss892714028 commented on etc/deploy_milvus_on_kubesphere.md
> +- Make sure your machine meets the minimal hardware requirement: CPU > 4 Core, Memory > 16 GB.
The minimum hardware spec for the Milvus cluster is 16c 64g https://milvus.io/docs/v2.0.x/prerequisite-docker.md

2022-03-22 08:48 UTC, ss892714028 approved these changes

2022-03-22 08:49 UTC, merged

2022-11-24 08:30 UTC, ruixiu commented
Error: error while running post render on files: error while running command /tmp/helm-operator/truk-reid_milvus-220_z3n3x751lj931o/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 49: mapping key "httpNumThreads" already defined at line 37 : exit status 1